export const GET_RESTOS = "GET_RESTOS";
export const CREATE_CLIENT = "CREATE_CLIENT";
export const CREATE_OWNER = "CREATE_OWNER";
export const GET_USERS = "GET_USERS";
export const GET_RESTO_NAME = "GET_RESTO_NAME";
export const GET_NEIGHBORHOODS = "GET_NEIGHBORHOODS";
export const GET_RESTO_DETAILS = "GET_RESTO_DETAILS";
export const CLEAR_DETAILS_STATE = "CLEAR_DETAILS_STATE";
export const POST_REVIEW = "POST_REVIEW";
export const GET_CUISINES = "GET_CUISINES";
export const LOADING = "LOADING";

